services:

  mongo:
    image: mongo:8
    container_name: clinic-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: clinic-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: clinic-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data: